# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Ur.create(id: 0, name: 'SELECCIONA' , responsible: '' , mail: '')
Ur.create(id: 1, name: 'LABORATORIO A-01 UR-306' , responsible: 'LARRIVA SAHD JORGE' , mail: 'jlsneuro@unam.mx')
Ur.create(id: 2, name: 'LABORATORIO A-02 UR-303' , responsible: 'CARABEZ TREJO ALFONSO' , mail: 'carabez1@unam.mx')
Ur.create(id: 3, name: 'LABORATORIO A-03 UR-308' , responsible: 'VARELA ECHAVARRIA ALFREDO' , mail: 'avarela@unam.mx')
Ur.create(id: 4, name: 'LABORATORIO A-13 UR-213' , responsible: 'PILONI ROJAS JOSE GERARDO' , mail: 'piloni@unam.mx')
Ur.create(id: 5, name: 'LABORATORIO A-14 UR-405' , responsible: 'CLAPP JIMENEZ LABORA MARIA DEL CARMEN' , mail: 'clapp@unam.mx')
Ur.create(id: 6, name: 'LABORATORIO A-15 UR-407' , responsible: 'MARTINEZ DE LA ESCALERA LORENZO GONZALO' , mail: 'gmel@unam.mx')
Ur.create(id: 7, name: 'LABORATORIO B-01 UR-406' , responsible: 'HEIMER EDGAR PHILIP' , mail: 'heimer@unam.mx')
Ur.create(id: 8, name: 'LABORATORIO B-04 UR-205' , responsible: 'PRADO ALCALA ROBERTO AGUSTIN' , mail: 'prado@unam.mx')
Ur.create(id: 9, name: 'LABORATORIO B-04 UR-206' , responsible: 'QUIRARTE GINA' , mail: 'ginaqui@unam.mx')
Ur.create(id: 10, name: 'LABORATORIO B-05 UR-310' , responsible: 'DE LA FUENTE FLORES VICTOR HUGO' , mail: 'lafuente@unam.mx')
Ur.create(id: 11, name: 'LABORATORIO B-06 UR-209' , responsible: 'HARMONY BAILLET THALIA' , mail: 'thaliah@unam.mx')
Ur.create(id: 12, name: 'LABORATORIO B-06 UR-211' , responsible: 'FERNANDEZ HARMONY THALIA' , mail: 'thaliafh@yahoo.com.mx')
Ur.create(id: 13, name: 'LABORATORIO B-11 UR-413' , responsible: 'DIAZ MUÑOZ MAURICIO' , mail: 'mdiaz@comunidad.unam.mx')
Ur.create(id: 14, name: 'LABORATORIO B-12 UR-410' , responsible: 'GARCIA COLUNGA JOSE JESUS' , mail: 'garciacolunga@unam.mx')
Ur.create(id: 15, name: 'LABORATORIO B-14 UR-212' , responsible: 'MIRANDA SAUCEDO MARIA ISABEL' , mail: 'mirandami@unam.mx')
Ur.create(id: 16, name: 'LABORATORIO B-15 UR-204' , responsible: 'MERCHANT NANCY HUGO' , mail: 'hugomerchant@unam.mx')
Ur.create(id: 17, name: 'LABORATORIO B-16 UR-309' , responsible: 'CONDES LARA MIGUEL' , mail: 'condes@servidor.unam.mx')
Ur.create(id: 18, name: 'LABORATORIO C-01 UR-304' , responsible: 'PEÑA ORTEGA FERNANDO' , mail: 'jfpena@unam.mx')
Ur.create(id: 19, name: 'LABORATORIO C-02 UR-305' , responsible: 'DIAZ MIRANDA SOFIA YOLANDA' , mail: 'yoldi@unam.mx')
Ur.create(id: 20, name: 'LABORATORIO C-03 UR-302' , responsible: 'SALAS ALVARADO MANUEL' , mail: 'masal@unam.mx')
Ur.create(id: 21, name: 'LABORATORIO C-12 UR-210' , responsible: 'BARRIOS ALVAREZ FERNANDO ALEJANDRO' , mail: 'barrios@inb.unam.mx')
Ur.create(id: 22, name: 'LABORATORIO D-01 UR-404' , responsible: 'ARAMBURO DE LA HOZ CARLOS' , mail: 'aramburo@unam.mx')
Ur.create(id: 23, name: 'LABORATORIO D-02 UR-403' , responsible: 'ACEVES VELASCO CARMEN YOLANDA' , mail: 'aceves@inb.unam.mx')
Ur.create(id: 24, name: 'LABORATORIO D-03 UR-402' , responsible: 'VALVERDE RODRIGUEZ CARLOS MANUEL' , mail: 'cavaro@unam.mx')
Ur.create(id: 25, name: 'LABORATORIO D-04 UR-307' , responsible: 'RIESGO ESCOVAR JUAN RAFAEL' , mail: 'riesgo@unam.mx')
Ur.create(id: 26, name: 'LABORATORIO D-05 UR-408' , responsible: 'MORALES GUZMAN MARIA TERESA' , mail: 'marter@unam.mx')
Ur.create(id: 27, name: 'LABORATORIO D-11 UR-203' , responsible: 'PAREDES GUERRERO RAUL GERARDO' , mail: 'rparedes@unam.mx')
Ur.create(id: 28, name: 'LABORATORIO D-12 UR-208' , responsible: 'GIORDANO NOYOLA MARIA MAGDALENA' , mail: 'giordano@unam.mx')
Ur.create(id: 29, name: 'LABORATORIO D-13 UR-412' , responsible: 'ARELLANO OSTOA ROGELIO' , mail: 'arellano.ostoa@comunidad.unam.mx')
Ur.create(id: 30, name: 'LABORATORIO D-15 UR-409' , responsible: 'MILEDI IDAU RICARDO' , mail: 'rmiledi@uci.edu')
Ur.create(id: 31, name: 'LABORATORIO D-15 UR-411' , responsible: 'MARTINEZ TORRES ATAULFO' , mail: 'ataulfo@unam.mx')
